### PR TITLE
sscode

### PR DESCRIPTION
**Pull request by theonlychant**

### CODE REVIEW

**Comment by adewynter** [comment]
Hi @1proprogrammerchant -- would you mind explaining how is this contributing to Clandestino?

**Comment by theonlychant** [comment]
its just a parse from the json just to assist I added javascript I added the node js as well sorry if this is causing any problems or wasting your time

**Comment by adewynter** [comment]
Hi @1proprogrammerchant  -- Not at all! We are definitely happy to take in contributions to the project. But in this case it seems to me that:
1. You still have not agreed to the CLA (and we cannot merge it)
2. node.js plug ins are not needed for this project.
I will close this one for now.
Best,

**Comment by theonlychant** [comment]
this may stupid and all but where can I argee to the CLA

**Pull request closed without merging**
